### ISSUE TITLE
Error in price update on steembottracker.com

### ISSUE THREAD

**Issue by RanjithPVRP** [ghasemkiani/steembottrackerapi#1]
ame: steembottracker
Respiratory: https://github.com/ghasemkiani/steembottrackerapi

#### Expected behaviour 
Shows the bid of bots and price with accuracy 
#### Actual behaviour
It shows wrong price of steem dollar. 
#### screenshot proof
 ![image](https://img.esteem.ws/gk0cp8uy5b.jpg)
Here it is the correct rate at steemit.com/market
 ![image](https://img.esteem.ws/1cokgl63db.jpg)

**Comment by ghasemkiani** [comment]
This repository gets information about bids from steembottracker.com, but it has no relationship with this website and has no control over it.

Besides, as far as I know, that website gets price information from coinmarketcap.com, and the CMC prices for steem-dollars have been recently at odds with most of the exchanges, including the internal market of the STEEM blockchain.
